server:
    port: 8888

spring: 
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://121.43.158.136:3306/boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: aaa85444
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
mybatis: 
    ##\u5B9E\u4F53\u7C7B\u8DEF\u5F84
    typeAliasesPackage: cn.xhg.ssm.pojo
    mapperLocations: classpath:mapper/*.xml
    
##logging: 
    level:
      cn.xhg.ssm.mapper.UserMapper: debug
      

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
